//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseAdsEntities : DbContext
    {
        public DatabaseAdsEntities()
            : base("name=DatabaseAdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credits> Credits1 { get; set; }
        public virtual DbSet<CreditsForGraphicArtist> CreditsForGraphicArtists { get; set; }
        public virtual DbSet<Orders> Orders1 { get; set; }
        public virtual DbSet<Templates> Templates1 { get; set; }
        public virtual DbSet<GraphicArtist> GraphicArtists { get; set; }
    }
}
