//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templates
    {
        public int TemplateKod { get; set; }
        public string TopPlace { get; set; }
        public string RightPlace { get; set; }
        public string WidthTemplate { get; set; }
        public string HeightTemplate { get; set; }
        public string PageTemplate { get; set; }
    }
}
